import {
  ARCHITECTURE_LABELS,
  FRAMEWORK_LABELS,
  summarizeDiff,
  type Blueprint,
  type BlueprintDiff,
} from "@backbone/core";
import type { BlueprintView } from "./helpers.js";
import type { Layout } from "./layout.js";
import type { GenFile, MigrationPlan } from "./types.js";

/**
 * Build GENERATION_REPORT.md — the traceability record mapping each frontend requirement
 * (with its source location) to the backend components that were generated from it.
 */
export function buildReport(args: {
  blueprint: Blueprint;
  view: BlueprintView;
  presetId: string;
  runtime: string;
  framework: string;
  architecture: string;
  layout: Layout;
  files: GenFile[];
  migrationFilename: string | null;
  plan: MigrationPlan;
  diff: BlueprintDiff | null;
  timestamp: string;
}): string {
  const { blueprint, view, presetId, runtime, framework, architecture, layout, files, migrationFilename, plan, diff, timestamp } = args;
  const L: string[] = [];

  const fwLabel = FRAMEWORK_LABELS[framework as keyof typeof FRAMEWORK_LABELS] ?? framework;
  const archLabel = ARCHITECTURE_LABELS[architecture as keyof typeof ARCHITECTURE_LABELS] ?? architecture;

  L.push(`# Generation report`);
  L.push("");
  L.push(`Generated by Backbone — deterministic, no AI at analyze or generate time.`);
  L.push("");
  L.push(`| | |`);
  L.push(`|---|---|`);
  L.push(`| Frontend | ${frontendLine(blueprint)} |`);
  L.push(`| Runtime | \`${runtime}\` |`);
  L.push(`| Framework | ${fwLabel} (\`${framework}\`) |`);
  L.push(`| Architecture | ${archLabel} (\`${architecture}\`) |`);
  L.push(`| Template set | \`${presetId}\` |`);
  L.push(`| Datastore | \`${view.dialect}\`${view.dialect === "sqlite" ? " (zero-setup default)" : ""} |`);
  L.push(`| Auth | ${view.hasAuth ? "JWT (register / login / me + guard)" : "none detected"} |`);
  L.push(`| Entities | ${view.entities.length} |`);
  L.push(`| Endpoints | ${view.entities.reduce((n, e) => n + e.endpoints.length, 0)} |`);
  L.push(`| Files written | ${files.length}${migrationFilename ? " + 1 migration" : ""} |`);
  L.push(`| Generated at | ${timestamp} |`);
  L.push("");

  // --- Architecture layering ---
  L.push(`## Architecture — ${layout.title}`);
  L.push("");
  L.push(`Dependency rule: ${layout.dependencyRule}.`);
  L.push("");
  L.push(`| Layer | Location | Responsibility |`);
  L.push(`|---|---|---|`);
  for (const layer of layout.layers) {
    L.push(`| ${layer.name} | \`${layer.path}\` | ${layer.role} |`);
  }
  L.push("");

  if (diff) {
    L.push(`## Change set (regeneration)`);
    L.push("");
    const lines = summarizeDiff(diff);
    if (lines.length === 0) {
      L.push(`No Blueprint changes since the last generation — code refreshed, no new migration.`);
    } else {
      L.push("```");
      lines.forEach((l) => L.push(l));
      L.push("```");
      if (plan.removedNotes.length) {
        L.push("");
        L.push(`Additive-only — the following were **not** applied (columns/tables kept):`);
        plan.removedNotes.forEach((n) => L.push(`- ${n}`));
      }
    }
    L.push("");
  }

  L.push(`## Frontend → backend traceability`);
  L.push("");
  for (const e of view.entities) {
    const src = blueprint.entities.find((x) => x.name === e.name);
    L.push(`### Entity \`${e.name}\` → table \`${e.table}\``);
    L.push("");
    if (src?.sourceRefs.length) {
      L.push(`Detected from ${src.sourceRefs.map((r) => `\`${r.file}:${r.line}\``).join(", ")}.`);
      L.push("");
    }
    L.push(`Generated: model, service, controller, zod validator, routes${migrationFilename ? ", migration" : ""}.`);
    L.push("");
    if (e.endpoints.length) {
      L.push(`| Method | Path | Operation | Auth | Source |`);
      L.push(`|---|---|---|---|---|`);
      for (const ep of e.endpoints) {
        const epSrc = blueprint.endpoints.find(
          (x) => x.method === ep.method && x.path === ep.httpPath,
        );
        const ref = epSrc?.sourceRefs[0];
        L.push(
          `| \`${ep.method}\` | \`${ep.httpPath}\` | ${ep.operation} | ${ep.auth ? "🔒" : "—"} | ${
            ref ? `\`${ref.file}:${ref.line}\`` : "—"
          } |`,
        );
      }
      L.push("");
    } else {
      L.push(`_No endpoints detected in the frontend; table generated for storage/relations._`);
      L.push("");
    }
    if (e.relations.length) {
      L.push(`Relations: ${e.relations.map((r) => `${r.kind} → \`${r.target}\``).join(", ")}.`);
      L.push("");
    }
  }

  if (view.hasAuth) {
    L.push(`## Auth`);
    L.push("");
    L.push(`Detected from a login/register call or bearer-token usage in the frontend.`);
    L.push(`Generated \`POST /auth/register\`, \`POST /auth/login\`, \`GET /auth/me\`, a JWT`);
    L.push(`verification middleware, a role guard, and a \`users\` table.`);
    if (view.auth.roles.length) L.push(`Roles: ${view.auth.roles.map((r) => `\`${r}\``).join(", ")}.`);
    L.push("");
  }

  L.push(`## Ownership boundary`);
  L.push("");
  L.push(`Everything under the generated boundary is owned by Backbone and overwritten on`);
  L.push(`every regenerate. Files outside it (the entrypoint, project config) are written`);
  L.push(`once and never touched again — your edits are safe. Migrations are additive: old`);
  L.push(`migrations are never edited or deleted.`);
  L.push("");

  return L.join("\n") + "\n";
}

/**
 * Build docs/ARCHITECTURE.md — a per-project explanation of the chosen architectural pattern:
 * its layers, where each lives, and the dependency rule that keeps the structure honest. Written
 * for every generated backend so the architecture axis is tangible in the output, not just a flag.
 */
export function buildArchitectureDoc(args: {
  framework: string;
  architecture: string;
  layout: Layout;
}): string {
  const { framework, architecture, layout } = args;
  const fwLabel = FRAMEWORK_LABELS[framework as keyof typeof FRAMEWORK_LABELS] ?? framework;
  const archLabel = ARCHITECTURE_LABELS[architecture as keyof typeof ARCHITECTURE_LABELS] ?? architecture;
  const L: string[] = [];

  L.push(`# Architecture — ${layout.title}`);
  L.push("");
  L.push(`This ${fwLabel} backend is organised using the **${archLabel}** pattern.`);
  L.push("");
  L.push(`**Dependency rule:** ${layout.dependencyRule}.`);
  L.push("");
  L.push(`## Layers`);
  L.push("");
  L.push(`The locations below name the pattern's canonical layers; a framework may use its own`);
  L.push(`idiomatic folder names for the same roles (e.g. \`routers/\` for the routing layer).`);
  L.push("");
  L.push(`| Layer | Location | Responsibility |`);
  L.push(`|---|---|---|`);
  for (const layer of layout.layers) {
    L.push(`| ${layer.name} | \`${layer.path}\` | ${layer.role} |`);
  }
  L.push("");
  L.push(`## Ownership`);
  L.push("");
  L.push(`Code inside the generated boundary is owned by Backbone and re-emitted on every`);
  L.push(`regenerate; the entrypoint and project configuration outside it are written once and`);
  L.push(`are yours to extend. Keeping the layering above intact keeps regeneration safe.`);
  L.push("");
  return L.join("\n");
}

/** One-line summary of the detected frontend framework for the report table. */
function frontendLine(bp: Blueprint): string {
  const f = bp.frontend;
  if (!f || !f.detected) return "undetected";
  const version = f.version ? ` ${f.version}` : "";
  const meta = f.meta ? ` (${f.meta})` : "";
  return `${f.displayName}${version}${meta}`;
}
