import { summarizeDiff, type Blueprint, type BlueprintDiff } from "@backbone/core";
import type { BlueprintView } from "./helpers.js";
import type { GenFile, MigrationPlan } from "./types.js";

/**
 * Build GENERATION_REPORT.md — the traceability record mapping each frontend requirement
 * (with its source location) to the backend components that were generated from it.
 */
export function buildReport(args: {
  blueprint: Blueprint;
  view: BlueprintView;
  presetId: string;
  runtime: string;
  architecture: string;
  files: GenFile[];
  migrationFilename: string | null;
  plan: MigrationPlan;
  diff: BlueprintDiff | null;
  timestamp: string;
}): string {
  const { blueprint, view, presetId, runtime, architecture, files, migrationFilename, plan, diff, timestamp } = args;
  const L: string[] = [];

  L.push(`# Generation report`);
  L.push("");
  L.push(`Generated by Backbone — deterministic, no AI at analyze or generate time.`);
  L.push("");
  L.push(`| | |`);
  L.push(`|---|---|`);
  L.push(`| Runtime | \`${runtime}\` |`);
  L.push(`| Architecture | \`${architecture}\` |`);
  L.push(`| Template set | \`${presetId}\` |`);
  L.push(`| Datastore | \`${view.dialect}\`${view.dialect === "sqlite" ? " (zero-setup default)" : ""} |`);
  L.push(`| Auth | ${view.hasAuth ? "JWT (register / login / me + guard)" : "none detected"} |`);
  L.push(`| Entities | ${view.entities.length} |`);
  L.push(`| Endpoints | ${view.entities.reduce((n, e) => n + e.endpoints.length, 0)} |`);
  L.push(`| Files written | ${files.length}${migrationFilename ? " + 1 migration" : ""} |`);
  L.push(`| Generated at | ${timestamp} |`);
  L.push("");

  if (diff) {
    L.push(`## Change set (regeneration)`);
    L.push("");
    const lines = summarizeDiff(diff);
    if (lines.length === 0) {
      L.push(`No Blueprint changes since the last generation — code refreshed, no new migration.`);
    } else {
      L.push("```");
      lines.forEach((l) => L.push(l));
      L.push("```");
      if (plan.removedNotes.length) {
        L.push("");
        L.push(`Additive-only — the following were **not** applied (columns/tables kept):`);
        plan.removedNotes.forEach((n) => L.push(`- ${n}`));
      }
    }
    L.push("");
  }

  L.push(`## Frontend → backend traceability`);
  L.push("");
  for (const e of view.entities) {
    const src = blueprint.entities.find((x) => x.name === e.name);
    L.push(`### Entity \`${e.name}\` → table \`${e.table}\``);
    L.push("");
    if (src?.sourceRefs.length) {
      L.push(`Detected from ${src.sourceRefs.map((r) => `\`${r.file}:${r.line}\``).join(", ")}.`);
      L.push("");
    }
    L.push(`Generated: model, service, controller, zod validator, routes${migrationFilename ? ", migration" : ""}.`);
    L.push("");
    if (e.endpoints.length) {
      L.push(`| Method | Path | Operation | Auth | Source |`);
      L.push(`|---|---|---|---|---|`);
      for (const ep of e.endpoints) {
        const epSrc = blueprint.endpoints.find(
          (x) => x.method === ep.method && x.path === ep.httpPath,
        );
        const ref = epSrc?.sourceRefs[0];
        L.push(
          `| \`${ep.method}\` | \`${ep.httpPath}\` | ${ep.operation} | ${ep.auth ? "🔒" : "—"} | ${
            ref ? `\`${ref.file}:${ref.line}\`` : "—"
          } |`,
        );
      }
      L.push("");
    } else {
      L.push(`_No endpoints detected in the frontend; table generated for storage/relations._`);
      L.push("");
    }
    if (e.relations.length) {
      L.push(`Relations: ${e.relations.map((r) => `${r.kind} → \`${r.target}\``).join(", ")}.`);
      L.push("");
    }
  }

  if (view.hasAuth) {
    L.push(`## Auth`);
    L.push("");
    L.push(`Detected from a login/register call or bearer-token usage in the frontend.`);
    L.push(`Generated \`POST /auth/register\`, \`POST /auth/login\`, \`GET /auth/me\`, a JWT`);
    L.push(`verification middleware, a role guard, and a \`users\` table.`);
    if (view.auth.roles.length) L.push(`Roles: ${view.auth.roles.map((r) => `\`${r}\``).join(", ")}.`);
    L.push("");
  }

  L.push(`## Ownership boundary`);
  L.push("");
  L.push(`Everything under the generated boundary is owned by Backbone and overwritten on`);
  L.push(`every regenerate. Files outside it (the entrypoint, project config) are written`);
  L.push(`once and never touched again — your edits are safe. Migrations are additive: old`);
  L.push(`migrations are never edited or deleted.`);
  L.push("");

  return L.join("\n") + "\n";
}
