/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: {
          900: "var(--ink-900)",
          800: "var(--ink-800)",
          700: "var(--ink-700)",
          600: "var(--ink-600)",
          500: "var(--ink-500)",
          400: "var(--ink-400)",
        },
        slate: { 300: "var(--slate-300)", 200: "var(--slate-200)" },
        paper: { 100: "var(--paper-100)" },
        brass: {
          600: "var(--brass-600)",
          500: "var(--brass-500)",
          400: "var(--brass-400)",
          "050": "var(--brass-050)",
        },
        verd: {
          600: "var(--verd-600)",
          500: "var(--verd-500)",
          400: "var(--verd-400)",
          "050": "var(--verd-050)",
        },
        danger: { 500: "var(--danger-500)", "050": "var(--danger-050)" },
        warn: { 500: "var(--warn-500)" },
        info: { 500: "var(--info-500)" },
        bg: "var(--bg)",
        surface: "var(--surface)",
        "surface-raised": "var(--surface-raised)",
        line: "var(--line)",
        rule: "var(--rule)",
        text: "var(--text)",
        "text-muted": "var(--text-muted)",
        detected: "var(--detected)",
        generated: "var(--generated)",
      },
      fontFamily: {
        display: "var(--font-display)",
        body: "var(--font-body)",
        mono: "var(--font-mono)",
      },
      borderRadius: {
        sm: "var(--r-sm)",
        DEFAULT: "var(--r-md)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        pill: "var(--r-pill)",
      },
      boxShadow: { pop: "var(--shadow-pop)" },
      letterSpacing: { eyebrow: "0.14em", tight: "-0.01em" },
      fontSize: {
        display: ["34px", { lineHeight: "38px" }],
        h1: ["24px", { lineHeight: "30px" }],
        h2: ["19px", { lineHeight: "26px" }],
        h3: ["16px", { lineHeight: "22px" }],
        body: ["14px", { lineHeight: "21px" }],
        small: ["13px", { lineHeight: "18px" }],
        mono: ["12.5px", { lineHeight: "18px" }],
        eyebrow: ["11px", { lineHeight: "14px" }],
      },
    },
  },
  plugins: [],
};
